import { Metadata } from "next";
import PrivacyPolicy from "./PrivacyPolicy";

// Server-side metadata export
export const metadata: Metadata = {
  title: "Privacy Policy - Sky Automobiles Motors, Maruti Suzukii",
  description: "Generated by create next app",
};

export default function PrivacyPolicyPage() {
  return <PrivacyPolicy />;
}
